# -*- coding: utf-8 -*-
"""LOGR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H61qbykzDXBFhgYK41OSi-4VX2ogF3Wn
"""

from google.colab import drive
drive.mount('/content/drive')

#Importing Libraries
import pandas as pd # Data Analysis and Manipulation
import numpy as np  # complex numerical Computation in the form of arrays and matrix
import seaborn as sns # Visualization tool

#NLP TOOLS for Text Preprocessing
import nltk
nltk.download('punkt_tab')

#Ignore warnings in output
import warnings
warnings.filterwarnings('ignore')

#Loading the Data
df = pd.read_csv('/content/drive/MyDrive/wrenchwise/emails.csv',encoding='latin1')
print("Data loaded successfully.")


#EDA --> Exploratory Data Analysis
#Summarize the Data
df.info()



df.head()

import re
import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer

# Set display options for full text visibility
pd.set_option('display.max_colwidth', None)

# Download necessary NLTK data
print("Downloading NLTK data...")
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
print("NLTK data download complete.")

# 1. Rename columns for clarity
df = df.rename(columns={'spam': 'type', 'text': 'message'})
print("\nColumns renamed: 'spam' to 'type', 'text' to 'message'")

# 2. Remove 'Subject: ' prefix from the 'message' column
df['message'] = df['message'].str.replace(r'^Subject: ', '', regex=True)
print("Removed 'Subject: ' prefix from 'message' column.")

df["No_of_Words"]=df.apply(lambda row: nltk.word_tokenize(row["message"]), axis=1).apply(len)
df.describe().T

import matplotlib.pyplot as plt
import seaborn as sns

# Create a subset DataFrame with the relevant columns for the pair plot
df_pairplot = df[['No_of_Words', 'type']]

# Visualize a pair plot to look for outliers in 'No_of_Words' across different 'type' categories
sns.pairplot(df_pairplot, hue='type', diag_kind='kde')
plt.suptitle('Pair Plot of No_of_Words vs. Type', y=1.02) # Adjust title position
plt.show()

import numpy as np

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for 'No_of_Words'
Q1 = df['No_of_Words'].quantile(0.25)
Q3 = df['No_of_Words'].quantile(0.75)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(f"Q1 (25th percentile): {Q1}")
print(f"Q3 (75th percentile): {Q3}")
print(f"IQR: {IQR}")
print(f"Lower Bound for Outliers: {lower_bound}")
print(f"Upper Bound for Outliers: {upper_bound}")

# Identify outliers
outliers = df[(df['No_of_Words'] < lower_bound) | (df['No_of_Words'] > upper_bound)]
print(f"\nNumber of outliers detected: {len(outliers)}")

# Remove outliers
df_no_outliers = df[(df['No_of_Words'] >= lower_bound) & (df['No_of_Words'] <= upper_bound)]

print(f"Original DataFrame shape: {df.shape}")
print(f"DataFrame shape after outlier removal: {df_no_outliers.shape}")

# Update the main DataFrame if you want to proceed without outliers
df = df_no_outliers.copy()
print("DataFrame updated with outliers removed.")

import matplotlib.pyplot as plt
import seaborn as sns

# Create a subset DataFrame with the relevant columns for the pair plot after outlier removal
df_pairplot_cleaned = df[['No_of_Words', 'type']]

# Visualize a pair plot of 'No_of_Words' vs. 'type' after outlier removal
sns.pairplot(df_pairplot_cleaned, hue='type', diag_kind='kde')
plt.suptitle('Pair Plot of No_of_Words vs. Type (After Outlier Removal)', y=1.02)
plt.show()

df.shape

df.describe().T

# 3. Text Cleaning Functions
# Function to remove special characters and numbers
def remove_special_characters_and_numbers(text):
    cleaned_text = re.sub(r'[^a-zA-Z\s]', '', text)
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    return cleaned_text

# Apply cleaning steps
print("\nApplying text cleaning and preprocessing steps...")
df['clean_message'] = df['message'].apply(remove_special_characters_and_numbers)

df.head()

# Function to tokenize text
def tokenize_text(text):
    return nltk.word_tokenize(text)
df['tokenized_message'] = df['clean_message'].apply(tokenize_text)
df.head()

# Function to remove stopwords
stop_words = set(stopwords.words('english'))
def remove_stopwords(tokens):
    return [word for word in tokens if word.lower() not in stop_words]
df['cleaned_message_no_stopwords'] = df['tokenized_message'].apply(remove_stopwords)
df.head()

# Function to lemmatize words
lemmatizer = WordNetLemmatizer()
def lemmatize_words(tokens):
    return [lemmatizer.lemmatize(word, pos='v') for word in tokens] # pos='v' for verb lemma
df['lemmatized_message'] = df['cleaned_message_no_stopwords'].apply(lemmatize_words)
df.head()

# Join the lemmatized words back into a string for TF-IDF
df['final_cleaned_text'] = df['lemmatized_message'].apply(lambda x: ' '.join(x))

print("Text cleaning and preprocessing steps completed.")
print("Displaying head of DataFrame with original message, type, and final cleaned text:")
print(df[['message', 'type', 'final_cleaned_text']].head())

# 4. TF-IDF Vectorization
print("\nStarting TF-IDF Vectorization...")
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df['final_cleaned_text'])
y = df['type'].values

print("TF-IDF Vectorization completed.")
print("Shape of TF-IDF vectors (X):", X.shape)
print("Shape of target variable (y):", y.shape)

import pandas as pd

# Display a few data points from the TF-IDF matrix (X)
# X is a sparse matrix, so we convert a small portion to a dense array/DataFrame for display
print("Displaying the first 5 rows and 10 columns of the TF-IDF matrix:")

# Get feature names from the TfidfVectorizer
feature_names = tfidf.get_feature_names_out()

# Convert the first 5 rows of the sparse matrix to a dense array
# And then to a DataFrame with corresponding feature names
tfidf_df = pd.DataFrame(X[:5, :].toarray(), columns=feature_names)

# Display the head of the DataFrame, possibly truncating columns for better display
# We'll display a fixed number of columns or all if there are few
if tfidf_df.shape[1] > 10:
    print(tfidf_df.iloc[:, :10]) # Display first 10 columns
else:
    print(tfidf_df)

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the distribution of the target variable (y)
plt.figure(figsize=(6, 4))
sns.countplot(x=y)
plt.title('Class Distribution (0: Ham, 1: Spam)')
plt.xlabel('Target Class')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels=['Ham', 'Spam'])
plt.show()

from sklearn.model_selection import train_test_split

# Split data into training and testing sets
# Assuming X and y are already defined from previous steps (TF-IDF Vectorization)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Data split into training and testing sets.")
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
import seaborn as sns


print("\nApplying SMOTE to balance the training data...")

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print(f"Shape of X_train before SMOTE: {X_train.shape}")
print(f"Shape of X_train after SMOTE: {X_train_smote.shape}")
print(f"Shape of y_train before SMOTE: {y_train.shape}")
print(f"Shape of y_train after SMOTE: {y_train_smote.shape}")

# Visualize the distribution of the target variable after SMOTE
plt.figure(figsize=(6, 4))
sns.countplot(x=y_train_smote)
plt.title('Class Distribution After SMOTE (0: Ham, 1: Spam)')
plt.xlabel('Target Class')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1], labels=['Ham', 'Spam'])
plt.show()

from sklearn.linear_model import LogisticRegression

# Initialize Logistic Regression model
log_reg_model = LogisticRegression(random_state=42, solver='liblinear', max_iter=1000)

print("Training Logistic Regression model...")
# Train the model using the SMOTE-resampled data
log_reg_model.fit(X_train_smote, y_train_smote)

print("Making predictions on the test data...")
y_pred = log_reg_model.predict(X_test)
print("Predictions completed.")

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)

print("Confusion Matrix:")
print(cm)
print(f"\nAccuracy: {accuracy:.4f}")

# Plotting the Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted Ham', 'Predicted Spam'],
            yticklabels=['Actual Ham', 'Actual Spam'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

# Print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

import joblib
import os

# Define the path to save the model and vectorizer in Google Drive
save_path = '/content/drive/MyDrive/wrenchwise/'
model_filename = os.path.join(save_path, 'logistic_regression_model.joblib')
vectorizer_filename = os.path.join(save_path, 'tfidf_vectorizer.joblib')

# Save the Logistic Regression model
joblib.dump(log_reg_model, model_filename)
print(f"Logistic Regression model saved to: {model_filename}")

# Save the TF-IDF vectorizer
joblib.dump(tfidf, vectorizer_filename)
print(f"TF-IDF vectorizer saved to: {vectorizer_filename}")































